FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-rc.2-alpine3.18 AS prepare
WORKDIR /app
RUN adduser -u 1000 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0.100-rc.2-alpine3.18 AS build
WORKDIR /code
COPY ./WebApp.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish \
    -c Release \
    -o /app \
    /p:PublishAot=false \
    --no-restore 

FROM prepare AS final
COPY --chown=appuser --from=build /app .